### ISSUE TITLE
Have network specific alerts for staking-miner-v2

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/polkadot-staking-miner#459]
We have alert if staking miner did not trigger any submissions:
```
alert:StakingMinerNoSubmissions 
expr:rate(staking_miner_submissions_started[5m]) == 0
for: 25h         <= session  time  + 1h 
```

Since session time is different for each network (e.g westend/kusama/polkadot) this alert will be correct for polkadot 24h but not for westend 6h 

Is it possible to expose session length as metrics?

**Comment by arminteimouri** [comment]
was discussed here:
https://matrix.to/#/!uCMSpHLvkFerxpASqc:parity.io/$LIgJNe-FJHj7JKnwB8LllFfByOPyax7o107EtJhxT_4?via=parity.io

**Comment by niklasad1** [comment]
Yes,

@BulatSaif

Would you prefer that we tag the metrics by network such as `staking_miner_kusama_submissions_started`?
Or just session length as a metric?

**Comment by BulatSaif** [comment]
> Would you prefer that we tag the metrics by network such as staking_miner_kusama_submissions_started?
Or just session length as a metric?

Just session length as a metric will be enough. 

Tag by the network should be done via labels example `staking_miner_submissions_started{chain="ksmcc3"}` (same as substrate metrics ) we don't need it now but may be useful for the future.

**Comment by BulatSaif** [comment]
Closing this issue, it can be addressed on the Grafana/Prometheus side.
