### ISSUE TITLE
docker tag for release v1.3.0

### ISSUE THREAD

**Issue by gabreal** [paritytech/polkadot-staking-miner#739]
github actions is [pushing to dockerhub](https://github.com/paritytech/polkadot-staking-miner/actions/runs/7245768687/job/19738095666#step:7:124), but [tagged release is not available](https://hub.docker.com/r/paritytech/polkadot-staking-miner/tags).

ref: https://github.com/paritytech/polkadot-staking-miner/pull/732

**Comment by niklasad1** [comment]
Yeah, I think it was my bad when I renamed the repo but will be fixed in the next release right @sergejparity?

**Comment by sergejparity** [comment]
Well. Actually v1.3.0 release was published before GHA which supposed to push to the new repo on hub.docker.com was merged. So you can delete and reapply the tag or just leave it as is and next release will be published under new name.

**Comment by niklasad1** [comment]
Gotcha, v1.3.0 is yanked anyway.

Thus, for the next tag we release this will be fixed

**Comment by niklasad1** [comment]
Treated this a one-off after [v1.3.1](https://hub.docker.com/layers/paritytech/polkadot-staking-miner/v1.3.1/images/sha256-e948760bf7e88a7925dca7e7cfbed7fbfb4ecbc2e21b8cd7b2edcc1a997e985f?context=explore) was published on docker hub.
