### ISSUE TITLE
Westend miner to skip the election submission one era every week

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-staking-miner#819]
In order to test the unsigned submission often in Westend, we could configure the Westend miner to skip the election submission during a full era every week (e.g. Monday pref so we are online if things go south).

cc @Ank4n

**Comment by kianenigma** [comment]
Westend runtime is still configured to not have a signed phase every now and then, so this is achieved. Or am I missing something?

**Comment by niklasad1** [comment]
I think it would easier just to turn-off the staking-miner by devops than to implement such thing in the staking-miner.

It's quite annoying to implement and we would to pass a flag that's westend and check the date on every sign phase but not that hard.

**Comment by gpestana** [comment]
> Westend runtime is still configured to not have a signed phase every now and then, so this is achieved.

I had a chat with @Ank4n and misunderstood that we don't have it anymore due to the merkelized metadata (https://github.com/paritytech/polkadot-sdk/pull/3646). But that doesn't really impact the calculation for when the signed phase is 0 since `SignedPhase` itself are constants.

Closing this.
