### ISSUE TITLE
Staking miner can't submit solution on current polkadot network 

### ISSUE THREAD

**Issue by btwiuse** [paritytech/polkadot-staking-miner#863]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The official polkadot staking miner failed to submit a working solution in a recent signed phase

The last solution was submitted by ocw in the unsigned phase:

https://polkadot.subscan.io/event?module=electionprovidermultiphase&event=all&timeType=block&version=9430&page=1&time_dimension=date&event_id=solutionstored

Related: https://github.com/paritytech/polkadot-staking-miner/issues/862

### Steps to reproduce

Run the staking miner during the signed phase and you'll see the tx submission failed with a runtime panic. Unfortunately I didn't preserve the error log and it can only be reproduced during the signed phase of an era

**Comment by niklasad1** [comment]
Hey @btwiuse thanks for reporting and keeping track of solutions but it's not an issue with the staking-miner itself rather than that an old version of staking-miner was used.

From our logs I can see:

```
submit_and_watch_solution failed: subxt error: `Extrinsic params error: The chain expects a signed extension with the name CheckMetadataHash, but we did not provide one`; skipping block: 21469614    
Mined solution with ElectionScore { minimal_stake: 24720303587938232, sum_stake: 8493905454717127157, sum_stake_squared: 244768888372659325923658462191981161 } size: SolutionOrSnapshotSize { voters: 22500, targets: 998 } round: 1195 at: 21469614, took: 20683 ms, len: 99522, weight = Weight { ref_time: 114899698320, proof_size: 12476069 }    
```

This is fixed https://github.com/paritytech/polkadot-staking-miner/releases/tag/v1.5.0
